<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YOUR FAVORITE TEAMS_Brooklyn-Nets</name>
   <tag></tag>
   <elementGuidId>344fafa3-2fe1-4da4-b032-4fce06e657fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Brooklyn-Nets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3af8af90-38f4-440c-8470-11373c5044bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Brooklyn-Nets</value>
      <webElementGuid>466d74e7-a517-4a29-ae91-21b572f56adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[3]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]/div[@class=&quot;team-picker mb-2&quot;]/button[@class=&quot;Brooklyn-Nets&quot;]</value>
      <webElementGuid>690659eb-fbad-4d5d-a009-9172c81efd91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/button[2]</value>
      <webElementGuid>f41fbf05-864a-4adf-a700-b0888e354dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>60a8356b-ba6c-4710-9670-76162b43cd96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
