<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>68af070c-ae30-456a-9783-c0e9d70b646d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;evergent iframe&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4d67b169-54a5-4494-a249-d9e6bb44113f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzUwNDkyMTYyMzM5NjQ1MCIsInNlcmlhbE5vIjoiZGJiYWM0YjAtMGFkYi0xMWVlLTg5YmYtYjE4ZDFjZjk5Yzk3IiwidWlkIjoiMjMwNjE0MTc1MDQ5MTYxIiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzY1MDQ0LCJleHAiOjE2ODY3Njg2NDksImlhdCI6MTY4Njc2NTA0OSwianRpIjoiRkFOZi1va2VOLWttQ0EtMjU3ay1LUzM3LUFYYUYtWjQiLCJjaWQiOiIzNjYyMDk2NCJ9.rUxXfrx3jPqQq8ZhoKuLcQb_qgCOWGdH_13vyLSdcwuNfkyNeMSqDun6UK4dPJ92DJHbYsnNijhBy7f2i_Pc9UVumowz1djdvf9Uv3qprEYX3fUXxBVuIUjv8GMa8XpdGVuuyCPGkUy0fxZ_U2O2YtvsbK1uNCOIpZ_0ARRlMUADeEiwkvvtryofSm4C1BU51nbzbSsFeYoZZaH5QTUWdMdxH_P547DGggiKtAel4MOpvvQXxedyTph2wwSkZJRJXRIx405IAFE4vxHSV0f95VEQx_5ho244zk-6KAupJU2_h1TwIR7E-PzTNOVOlhLm0LKcuZNLdKIqNP7KQRelK0kKyn7nYXBOw6mQPJImYlJdkEUsrfb90ablUD_jav6CXPZoDfrkpkKKkJp98guzLAEN08PzJtOLinujl1iDOHXd689aPh4QIAULhqnmpUNyDo9KmhF0MNlFSV2ufn9ht2jq-yqZt6m-MC0sYzc8pcqC2fVN_zy-QlnG-0VcbZ8eEjEhFc6Cp0eKVKv0CIiwOY7KEg5ph7mwNrHKeEG_UtKoYkH-3gmN4GmDmRG80cIJ1Hri0PyP87LRUBNP6pq-V4gE3qHSPbr0w9nFYOcxUMaBgK9tAtpnC4FtEqwZPpcC8ZNYcpbpXT4t-7_Y0uGSchIHqryUQNeWbtwAi0IEziQ&amp;cpCustomerId=230614175049161&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686765065.245</value>
      <webElementGuid>1142831c-a1a1-4502-8be4-868c5dde3d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>8f36c2ba-fd78-4a25-979c-04118a54c145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>2aa4324e-2fec-427e-b40d-ea5d6cdc92ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>evergent iframe</value>
      <webElementGuid>8f5392b0-177e-4fee-a77b-eb8f348ea101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>052fd5ee-bfec-4f14-ae92-9fbc5f1c5ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[@class=&quot;credit-card-screen row&quot;]/div[@class=&quot;payment-section col&quot;]/iframe[1]</value>
      <webElementGuid>10cf7bfc-6c7c-4188-9dd2-1fdca1ce24ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      <webElementGuid>a8d649e6-2b95-4497-b754-8657a939b606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>87836794-59b4-4bc6-8d23-841b2be0760f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzUwNDkyMTYyMzM5NjQ1MCIsInNlcmlhbE5vIjoiZGJiYWM0YjAtMGFkYi0xMWVlLTg5YmYtYjE4ZDFjZjk5Yzk3IiwidWlkIjoiMjMwNjE0MTc1MDQ5MTYxIiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzY1MDQ0LCJleHAiOjE2ODY3Njg2NDksImlhdCI6MTY4Njc2NTA0OSwianRpIjoiRkFOZi1va2VOLWttQ0EtMjU3ay1LUzM3LUFYYUYtWjQiLCJjaWQiOiIzNjYyMDk2NCJ9.rUxXfrx3jPqQq8ZhoKuLcQb_qgCOWGdH_13vyLSdcwuNfkyNeMSqDun6UK4dPJ92DJHbYsnNijhBy7f2i_Pc9UVumowz1djdvf9Uv3qprEYX3fUXxBVuIUjv8GMa8XpdGVuuyCPGkUy0fxZ_U2O2YtvsbK1uNCOIpZ_0ARRlMUADeEiwkvvtryofSm4C1BU51nbzbSsFeYoZZaH5QTUWdMdxH_P547DGggiKtAel4MOpvvQXxedyTph2wwSkZJRJXRIx405IAFE4vxHSV0f95VEQx_5ho244zk-6KAupJU2_h1TwIR7E-PzTNOVOlhLm0LKcuZNLdKIqNP7KQRelK0kKyn7nYXBOw6mQPJImYlJdkEUsrfb90ablUD_jav6CXPZoDfrkpkKKkJp98guzLAEN08PzJtOLinujl1iDOHXd689aPh4QIAULhqnmpUNyDo9KmhF0MNlFSV2ufn9ht2jq-yqZt6m-MC0sYzc8pcqC2fVN_zy-QlnG-0VcbZ8eEjEhFc6Cp0eKVKv0CIiwOY7KEg5ph7mwNrHKeEG_UtKoYkH-3gmN4GmDmRG80cIJ1Hri0PyP87LRUBNP6pq-V4gE3qHSPbr0w9nFYOcxUMaBgK9tAtpnC4FtEqwZPpcC8ZNYcpbpXT4t-7_Y0uGSchIHqryUQNeWbtwAi0IEziQ&amp;cpCustomerId=230614175049161&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686765065.245' and @title = 'evergent iframe']</value>
      <webElementGuid>5f61f877-4010-4d00-a741-cd57c7e2dffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
