<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5ea3ad5d-aa9f-4d01-8f36-30ee6e5d6f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Settings&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ebf2bc74-2977-43fa-8a90-efa3c8a34e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/account_icon.ebabf13f.svg</value>
      <webElementGuid>9890c47f-7441-431e-9a80-88c103be5dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>9d34983a-fb36-41be-b121-92343bf7d066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;d-flex justify-content-between search-section&quot;]/div[@class=&quot;settings-icon&quot;]/img[1]</value>
      <webElementGuid>632d5324-f51d-4aa9-9bf1-86ab01dd25d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/img</value>
      <webElementGuid>61060e1f-8f04-4f7c-856d-35506cb7a903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Settings']</value>
      <webElementGuid>da2ccdf6-9fe5-4bd7-846e-9b3732f8b122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>67358c79-39a3-40c3-99ed-421a16a2a1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/account_icon.ebabf13f.svg' and @alt = 'Settings']</value>
      <webElementGuid>40ed9435-4386-4462-bbea-7298c20af2e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
