<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_19.99_termsconditions</name>
   <tag></tag>
   <elementGuidId>a2c1cbdf-8b96-4a00-9a30-166106fa8851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;termsconditions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='termsconditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fde2878e-b22f-40ce-b39b-702f656427ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss7</value>
      <webElementGuid>03cea7b9-7ba8-45ee-9876-9ebbc6cef6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>9f5b71bb-137d-4cc3-a42f-0928749ccf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f703def-5c0a-4d29-9052-54a78f69efc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8108e763-8b44-4259-81cd-1f18979ced06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>926d572a-839f-4b74-a6c5-712edbc4fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrap h-100&quot;]/div[@class=&quot;checkout_wrapper&quot;]/div[@class=&quot;MuiGrid-root checkout_container py-2 MuiGrid-container MuiGrid-justify-content-xs-center&quot;]/div[@class=&quot;MuiGrid-root paymentMethod_inner&quot;]/div[@class=&quot;jss1&quot;]/form[1]/div[@class=&quot;MuiGrid-root placeOrder_block checkBoxContainer mb-3&quot;]/div[1]/label[@class=&quot;MuiFormControlLabel-root&quot;]/div[1]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss4 MuiCheckbox-root MuiCheckbox-colorSecondary MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss7&quot;]</value>
      <webElementGuid>0ddd134c-6152-4768-bd16-a8d4ed6312b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Registration_Settings/Page_Watch  YES Network/iframe</value>
      <webElementGuid>0d9a73f9-f975-42df-bc37-51db649fb70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='termsconditions']</value>
      <webElementGuid>491dfb0c-ddff-45bf-8b9c-4c07ff6fff1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[3]/div/label/div/span/span/input</value>
      <webElementGuid>5e312ff6-ee23-405b-8e2a-c5f4dd49095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>e40578b6-5f80-4785-98ea-fc7397fbf27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'termsconditions' and @type = 'checkbox']</value>
      <webElementGuid>dc961bb4-6e2b-4aa6-ab53-289df6271b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
