<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discount Code_discountCode</name>
   <tag></tag>
   <elementGuidId>230168e1-29ac-40d6-a72a-566618d7b537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#discountCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='discountCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64a2c668-ad76-4235-9a3f-d67d07e68fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>384414be-375f-40ba-9612-b61c27d258c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discountCode</value>
      <webElementGuid>c6930500-c8fa-416c-9b02-a6342ccdabe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discountCode</value>
      <webElementGuid>1da0f1f9-9cf4-4d28-994a-f3f0ff201ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acca0010-7215-4303-b6a3-203f37e07a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input</value>
      <webElementGuid>e562ba8b-2469-4ab0-87bf-ed49aa43482f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discountCode&quot;)</value>
      <webElementGuid>88da7600-422b-42d0-b1a2-234e612efb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Registration_Settings/Page_Watch  YES Network/iframe</value>
      <webElementGuid>6738a7b5-ec10-4271-886f-90405229ad77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='discountCode']</value>
      <webElementGuid>4456622a-efd1-4448-b8f5-adc2d0d43517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>dd29fc2e-1c10-4d1b-97da-e19850c4e596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>f8be6358-b8cf-454f-94d5-0c89cdb4038b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'discountCode' and @name = 'discountCode' and @type = 'text']</value>
      <webElementGuid>c8b13c08-7c55-4c6e-b7ff-296e178c3e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
