<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card_nameOnCard</name>
   <tag></tag>
   <elementGuidId>e283cc91-0006-4df9-bac8-df1f2c00df93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameOnCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameOnCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f0542a2-fde1-4b59-9787-c691c27f07f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e36208e-3c04-4fb8-a2e2-f6bc5494c429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>a88fff75-3c48-4d86-99e2-692e67703c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>f99da4d6-0bb8-4295-9e3f-775d840ddcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a74a9162-9834-4be3-9cba-4b7aa8578b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input</value>
      <webElementGuid>14b25981-eb59-450c-a0ce-2bd4bae949ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameOnCard&quot;)</value>
      <webElementGuid>13eaef40-745d-4281-9e3c-1707e1986ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Registration_Settings/Page_Watch  YES Network/iframe</value>
      <webElementGuid>239082d8-6823-4ad5-9b12-4d32e35c38e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameOnCard']</value>
      <webElementGuid>409fbea5-52b4-4127-92cf-57ff5b9f33d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>c9f0c380-d1c5-4f80-9a9f-50151745b190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cbbf970a-803b-4820-8794-115f668ac160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nameOnCard' and @name = 'nameOnCard' and @type = 'text']</value>
      <webElementGuid>3c31b4b9-9fa8-4171-b4d5-550d963d8666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
