<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OptionalMaleFemaleOtherPrefer not to answer</name>
   <tag></tag>
   <elementGuidId>5b2c701a-e1f4-45a1-af79-37622de3f228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;gender&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='gender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de38d1bc-482a-4be5-b342-b58b23e5504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>8dfd45e1-851f-4a8b-9be0-8472bb13010a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gender-dropdown</value>
      <webElementGuid>7173fba6-7df3-4fd7-91f2-e14f37d2c486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OptionalMaleFemaleOtherPrefer not to answer</value>
      <webElementGuid>13424d57-2dca-4a17-870a-128188a28a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[3]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]/form[@class=&quot;register&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control gender-dropdown&quot;]</value>
      <webElementGuid>65276e67-1fc5-4133-96fd-ec504804fbef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='gender']</value>
      <webElementGuid>8cc1849e-b92d-47df-8d74-41b838ab1df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/form/div[4]/div[2]/div/select</value>
      <webElementGuid>6aac589a-b993-40d7-9824-1e357a20ba6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[1]/following::select[1]</value>
      <webElementGuid>15374228-63b2-44ee-8e3f-ce8850ff94b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Never miss a moment! Share your email to receive our newsletter and updates.'])[1]/preceding::select[1]</value>
      <webElementGuid>6eed5e90-61e2-4620-91e5-bfb34356defb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9c41dbd9-9a51-40e1-8e34-0412e06a5f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'gender' and (text() = 'OptionalMaleFemaleOtherPrefer not to answer' or . = 'OptionalMaleFemaleOtherPrefer not to answer')]</value>
      <webElementGuid>c34fd2e7-2bda-4e95-bfcd-d0f0368950bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
