<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MAYBE LATER</name>
   <tag></tag>
   <elementGuidId>aad8d5f6-5d20-4a52-8b3e-b4998b60b1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.link-blue.pts-b-db-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div/div[2]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21f17460-af97-4262-8f9a-9c4ad381034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-blue pts-b-db-20</value>
      <webElementGuid>6fac31c9-710d-4d09-a19c-5df071325d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAYBE LATER</value>
      <webElementGuid>2e8484e7-ceb1-46ac-8bf8-e594a5bc2008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[3]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]/div[1]/div[@class=&quot;onboarding-fav-players col-md-14&quot;]/div[@class=&quot;btn-done-section-onboarding d-flex justify-content-around align-items-center flex-column&quot;]/span[@class=&quot;link-blue pts-b-db-20&quot;]</value>
      <webElementGuid>5866e072-e950-4c99-b575-c86c4a5e773a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div[2]/div[3]/span</value>
      <webElementGuid>5dbe5d8a-f99e-4ff3-a51b-c17557c8202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LET’S GO'])[1]/following::span[1]</value>
      <webElementGuid>cb78d77b-010d-4b3a-ae60-968b03b27fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liberty'])[1]/following::span[1]</value>
      <webElementGuid>d3f79206-4ce6-4e64-b116-547dc0ce2caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MAYBE LATER']/parent::*</value>
      <webElementGuid>adbbc9b4-e035-4e26-9ef3-db80756902f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>74ac3f83-4193-47ee-b6fc-3c0d709f3fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MAYBE LATER' or . = 'MAYBE LATER')]</value>
      <webElementGuid>8a378d3f-814f-423e-83b7-c11c525cac04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
