<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Skip navigation_container</name>
   <tag></tag>
   <elementGuidId>6d5aecdb-2da7-4f23-872b-57607ef9c198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-form > #container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='container'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f98e2a90-7ae4-4a62-a936-2accdabaa5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>fe4d7b09-f188-4525-88f2-14a8acbd5748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-searchbox</value>
      <webElementGuid>352a81a7-d14c-46f3-a7aa-8999dd33a681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-form&quot;)/div[@id=&quot;container&quot;]</value>
      <webElementGuid>2d3544e5-3126-410d-89da-88bd90298ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='container'])[3]</value>
      <webElementGuid>b5ea7038-5929-4c59-a782-a5c04061f19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-form']/div</value>
      <webElementGuid>89862f67-4864-4056-ad4a-f4747a9454ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation'])[1]/following::div[5]</value>
      <webElementGuid>1d260313-8a03-44bb-a1b7-56ae855a5541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA'])[1]/following::div[7]</value>
      <webElementGuid>a32c1bc4-6985-4f49-93de-74ee7d1af978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::div[9]</value>
      <webElementGuid>3b217421-fb89-4e78-a991-a7fdac7dbff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>cbaf2f74-5d4f-4c72-9433-653dd7be4a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container']</value>
      <webElementGuid>e3c8a373-d7ce-48a6-8dc4-0ffe96c5f2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
