<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YOUR FAVORITE TEAMS_Brooklyn-Nets</name>
   <tag></tag>
   <elementGuidId>f889e949-c19d-4abf-9ce2-ea7b55435d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Brooklyn-Nets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a570d562-14ed-41a3-a448-51263dae397e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Brooklyn-Nets</value>
      <webElementGuid>21472653-cc05-42a9-a470-edcb02f87aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[3]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]/div[@class=&quot;team-picker mb-2&quot;]/button[@class=&quot;Brooklyn-Nets&quot;]</value>
      <webElementGuid>e1ef860a-bb23-40ed-bdc0-b76dcbc37313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/button[2]</value>
      <webElementGuid>2823d277-427a-4479-b9da-6686a86006d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>67c557c9-e199-4d79-abcb-7eebcc77b09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
