<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SUBSCRIBE</name>
   <tag></tag>
   <elementGuidId>05e420c0-a1b8-471c-ae35-6f1336ecb5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.primary__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b960fb4-b4af-49dc-953d-fe486341ec2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary__button</value>
      <webElementGuid>3a1f3c49-6cda-45d3-b336-2d46ea51b8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUBSCRIBE</value>
      <webElementGuid>c9dcdfee-6004-4d3c-8b11-0f560096120d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background subscriber-page&quot;]/div[@class=&quot;subscribe-page&quot;]/div[@class=&quot;subscribe-content&quot;]/button[@class=&quot;primary__button&quot;]</value>
      <webElementGuid>bb52de34-304b-4d24-a5fe-1d489de25d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/button</value>
      <webElementGuid>826f66b4-2f5f-4af9-bb4b-e413cbb8586a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject to territorial restrictions.'])[1]/following::button[1]</value>
      <webElementGuid>0247b7bd-10cc-4e3e-85e6-f2bad02d0b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe now for just $24.99'])[1]/following::button[1]</value>
      <webElementGuid>1ac57bab-b966-419e-a446-8f0d070fdc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUBSCRIBE']/parent::*</value>
      <webElementGuid>0bd5d092-e245-4130-b5c3-b9696064fb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>cb825fb4-e727-4975-9fa6-20efbbda1783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SUBSCRIBE' or . = 'SUBSCRIBE')]</value>
      <webElementGuid>df1a23a0-2c28-401d-a335-38ef0d020cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
