<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_On Now</name>
   <tag></tag>
   <elementGuidId>f9d4e737-47aa-4a46-bed9-a4b230175083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.tgd1-b-base-33.float-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ab63a058-72ee-4d32-8834-40555c4ffca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgd1-b-base-33 float-left</value>
      <webElementGuid>5f41c37d-4a8e-40a4-9748-f174962bbbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Now</value>
      <webElementGuid>ff7c6212-b50d-43ac-979e-b72d86b058f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;player-container d-flex flex-column&quot;]/div[@class=&quot;watch-header d-flex align-items-center justify-content-between mb-2&quot;]/h3[@class=&quot;tgd1-b-base-33 float-left&quot;]</value>
      <webElementGuid>49452618-bd4b-4850-a902-09bc41450faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/h3</value>
      <webElementGuid>fa833905-df88-4680-a325-618179f7b2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play/Pause'])[1]/preceding::h3[1]</value>
      <webElementGuid>6c7ff9fc-e2e9-4a5d-b9d4-b0522f89f4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Quality'])[1]/preceding::h3[1]</value>
      <webElementGuid>e7196bf8-93a0-4427-94a9-9a608f5691d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On Now']/parent::*</value>
      <webElementGuid>2e8dcb10-91be-4350-92bc-49be0fdb45a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>fc17ccc9-b644-4ee7-9a9b-36663b1bcb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'On Now' or . = 'On Now')]</value>
      <webElementGuid>58f0d2e0-6fdd-4c26-93f7-c1801b12511b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
