<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>2722c38d-eb8a-4666-bce3-a6e2c97e1c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;evergent iframe&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9868ab42-7b72-467b-87c5-114412d13cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzQwMDkyMzQyMzM5ODI1MCIsInNlcmlhbE5vIjoiNWM3NThjZTAtMGFkYS0xMWVlLWExMGYtZjdiZmRjNmNlOTM5IiwidWlkIjoiMjMwNjE0MTc0MDA5MTkwIiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzY0NDA0LCJleHAiOjE2ODY3NjgwMDksImlhdCI6MTY4Njc2NDQwOSwianRpIjoiVExIdy1OWmtxLWhSaHItRnlTaC1rbjNQLU93ZW0tNUYiLCJjaWQiOiIzNjYyMjc2NCJ9.TVgu2KA28KPPhwF_TnZE1wEnprROhpmrBQ8Xk3FN8qxPMypGOONTQWKM6IIPIoEtdG_Bmj3zNcZOVZFQC_YnO2R_DfjrZrSSFHRGFnfACflbCb3kaQ_l-2aToKS4fufSMA87Efn0aPPIkCzt36ZJsXU6Uz44eI-tx-7nppyDrGwRnV7cqRM9MMTdp1Gwc9DUA5eGb5W84YtPQkZ27znUcafsLMI3mX9-K348d0Qq96U5qgxf78g0Cj838LBdXudC8A7jG9ggifnF49FyP0oHl08JtDSTdGIzkUh0gg51OhLmV5ZzFnG6PA1iINMJPGEYfxbpRBItob2C-Z7dhtJwgpntgExuGQvOR23T51yiEZFtgVTXWJUFR82ZATXSYvSDPtchLQtVY6IhrFtB0SJ6hHwoLInBQ3fwy8pp8NLRMtA__ptjlpLGkoJarPFtzVw-IxE_0LRD0g83RDj1sDU3VKm83TJT8HBE333RpFHU2IQFlMp9QXY_BabkdUk_GnBNhrnCF4gBkm8IXlm90gdZan6yWhnJI56XHo-FDPdu41p7S7fnnHb81fps6YpPuXLmD3OYSbPqs4N5YNrR4cyXOUnj_mrZj6O78n0MjHldxclgQrp87klyxbeQYripCFS_hKWyCRXxMtGWn3VH_xs5zdetQpISRcNKl1QLwfL45kE&amp;cpCustomerId=230614174009190&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686764427.492</value>
      <webElementGuid>2abc80dd-f854-4ec6-adb1-743b5f483fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>47ee660f-342e-495d-831d-2a227a75c55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>f06be307-2735-4362-a976-5ca9273989a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>evergent iframe</value>
      <webElementGuid>0c5e0228-3ae4-4d9d-b2c8-7b4b3a829594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fae61165-3591-4cf9-9a72-5bd358ce2c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[@class=&quot;credit-card-screen row&quot;]/div[@class=&quot;payment-section col&quot;]/iframe[1]</value>
      <webElementGuid>d6c8e35e-1f13-42fb-ba83-4a06d68e4643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      <webElementGuid>3a2ec06c-fad4-4dfb-8ab6-9eaf8b053743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>b5fa4e1b-e2a0-476a-8bc7-ec9f32b747f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzQwMDkyMzQyMzM5ODI1MCIsInNlcmlhbE5vIjoiNWM3NThjZTAtMGFkYS0xMWVlLWExMGYtZjdiZmRjNmNlOTM5IiwidWlkIjoiMjMwNjE0MTc0MDA5MTkwIiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzY0NDA0LCJleHAiOjE2ODY3NjgwMDksImlhdCI6MTY4Njc2NDQwOSwianRpIjoiVExIdy1OWmtxLWhSaHItRnlTaC1rbjNQLU93ZW0tNUYiLCJjaWQiOiIzNjYyMjc2NCJ9.TVgu2KA28KPPhwF_TnZE1wEnprROhpmrBQ8Xk3FN8qxPMypGOONTQWKM6IIPIoEtdG_Bmj3zNcZOVZFQC_YnO2R_DfjrZrSSFHRGFnfACflbCb3kaQ_l-2aToKS4fufSMA87Efn0aPPIkCzt36ZJsXU6Uz44eI-tx-7nppyDrGwRnV7cqRM9MMTdp1Gwc9DUA5eGb5W84YtPQkZ27znUcafsLMI3mX9-K348d0Qq96U5qgxf78g0Cj838LBdXudC8A7jG9ggifnF49FyP0oHl08JtDSTdGIzkUh0gg51OhLmV5ZzFnG6PA1iINMJPGEYfxbpRBItob2C-Z7dhtJwgpntgExuGQvOR23T51yiEZFtgVTXWJUFR82ZATXSYvSDPtchLQtVY6IhrFtB0SJ6hHwoLInBQ3fwy8pp8NLRMtA__ptjlpLGkoJarPFtzVw-IxE_0LRD0g83RDj1sDU3VKm83TJT8HBE333RpFHU2IQFlMp9QXY_BabkdUk_GnBNhrnCF4gBkm8IXlm90gdZan6yWhnJI56XHo-FDPdu41p7S7fnnHb81fps6YpPuXLmD3OYSbPqs4N5YNrR4cyXOUnj_mrZj6O78n0MjHldxclgQrp87klyxbeQYripCFS_hKWyCRXxMtGWn3VH_xs5zdetQpISRcNKl1QLwfL45kE&amp;cpCustomerId=230614174009190&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686764427.492' and @title = 'evergent iframe']</value>
      <webElementGuid>dea0786c-c622-4d08-b2d9-035a8684cf82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
