<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_19.99_termsconditions</name>
   <tag></tag>
   <elementGuidId>e0c7b08f-b90e-4e1c-93d9-e27c4dbe16ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;termsconditions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='termsconditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a206011a-98ea-4a67-b968-beb7b81d9999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss7</value>
      <webElementGuid>dd7a6a24-9be0-4988-9b3f-73995e3bdae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>359bb335-9584-4b1d-92ce-6d74adbcb044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>abb8faa3-07d2-4541-9adf-759c26070f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f58231f-64e3-4739-a539-fc6e6d96da17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>46b3fcaa-7b6e-4463-bb4e-5286386b5812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrap h-100&quot;]/div[@class=&quot;checkout_wrapper&quot;]/div[@class=&quot;MuiGrid-root checkout_container py-2 MuiGrid-container MuiGrid-justify-content-xs-center&quot;]/div[@class=&quot;MuiGrid-root paymentMethod_inner&quot;]/div[@class=&quot;jss1&quot;]/form[1]/div[@class=&quot;MuiGrid-root placeOrder_block checkBoxContainer mb-3&quot;]/div[1]/label[@class=&quot;MuiFormControlLabel-root&quot;]/div[1]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss4 MuiCheckbox-root MuiCheckbox-colorSecondary MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss7&quot;]</value>
      <webElementGuid>b308d618-50eb-4fe3-8b0e-37668809f4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Watch_Screen_Subscribe/Page_Watch  YES Network/iframe</value>
      <webElementGuid>0e68924e-ab82-45cc-a420-784cfa053db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='termsconditions']</value>
      <webElementGuid>a66d04cc-1de9-4dae-b4a4-1a1a61b81b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[3]/div/label/div/span/span/input</value>
      <webElementGuid>2de715df-d077-4733-a58f-69da591b6d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4c5f233d-800a-40de-a59e-2c6fe04ce3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'termsconditions' and @type = 'checkbox']</value>
      <webElementGuid>869b945f-eb80-4aec-9104-3e8e0f2b6490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
