<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exp MMYY_expiryDate</name>
   <tag></tag>
   <elementGuidId>83d720c1-dff6-4615-ac3e-924986a8934a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>706dc89f-e43a-4a3b-8ddf-9e687477688b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>776f9b49-7202-46f1-80f5-1783697fab11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>20d4e063-0b80-4d9a-81b6-c6a0be69b876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>c0e562f4-00eb-4ebc-aaf7-50e1191ce59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>05781a18-3b34-4778-a53c-1f7a123a1b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>77b15eec-cc86-4f91-85a3-f78459e011c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>393c426f-ace1-445d-88ab-cf1a8c287c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input</value>
      <webElementGuid>175533cf-5214-4509-8cf9-ccc0352dcfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8a39a7d-bb7f-46ed-a227-0317e39d446b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiryDate&quot;)</value>
      <webElementGuid>8248fab8-807a-4be1-be12-1b1d0feef4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Watch_Screen_Subscribe/Page_Watch  YES Network/iframe</value>
      <webElementGuid>7c3da1de-0be1-42a6-830a-d40d66ea9d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiryDate']</value>
      <webElementGuid>56d78324-531b-4d04-b373-e8524d3ac1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[4]/div/div/div/input</value>
      <webElementGuid>3495499a-a8a0-4805-a750-1cbe593cb527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>5dcb8399-6a17-4646-b71f-07d69eaf2f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiryDate' and @name = 'expiryDate' and @type = 'tel']</value>
      <webElementGuid>fb8116b9-d4e1-43ab-b531-fb6897cc2c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
