<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_On Now</name>
   <tag></tag>
   <elementGuidId>08ad27b7-b423-4f16-bb7f-c4fa8f3b5b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.tgd1-b-base-33.float-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>b3966a06-24df-487d-9091-7d04208cbf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgd1-b-base-33 float-left</value>
      <webElementGuid>19434bc7-dffb-48ff-b72f-151147bf2b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Now</value>
      <webElementGuid>a6b2a2ad-58e6-439c-b738-8558876a53b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;player-container d-flex flex-column&quot;]/div[@class=&quot;watch-header d-flex align-items-center justify-content-between mb-2&quot;]/h3[@class=&quot;tgd1-b-base-33 float-left&quot;]</value>
      <webElementGuid>31a636c5-7739-4bb1-92c6-38cc2d0109f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/h3</value>
      <webElementGuid>c66114fa-4d8a-4b02-9e9f-e30f26e066bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play/Pause'])[1]/preceding::h3[1]</value>
      <webElementGuid>882840c4-047a-40eb-b084-4a04ba78211b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Quality'])[1]/preceding::h3[1]</value>
      <webElementGuid>1f4f1d29-eabd-4790-856a-e432577f61ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On Now']/parent::*</value>
      <webElementGuid>da20e48d-d598-4b48-a5e4-fb46bf5a8de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>4e852d68-ddba-456e-b45a-31379565ad5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'On Now' or . = 'On Now')]</value>
      <webElementGuid>add5223f-81a5-477b-ae90-1c0ddcd48eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
