<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>ad14a35d-6aff-44ee-8618-12649ab3a253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;evergent iframe&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e6eddcff-d06c-4662-9de5-baa1a1d70a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzA4NDE3NTAyMzQwMDQ1NyIsInNlcmlhbE5vIjoiZmY2MWRlZTAtMGFkNS0xMWVlLWI0OTUtYmQ0Y2NiYTk1MzQ5IiwidWlkIjoiMjMwNjE0MTcwODQxNzE4IiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzYyNTE2LCJleHAiOjE2ODY3NjYxMjEsImlhdCI6MTY4Njc2MjUyMSwianRpIjoiMVl0WC1FcjExLTBXWk0td2lnNC1jUkFaLTNUTnItNWQiLCJjaWQiOiIzNjYyNDk3MSJ9.DEKLuirxnULyRL8mw6mBtnEOFfbJdXmdxNmMSi210oTZR3EPBxsolfTyWItWwTTdijHxtjVUhS9RRDfDeB5ZoyFvM7LTSXT5AC-XDM90Ici7P7uZWiGoth7C__Ouucnws-0MIWBtOA6J0S7zVesERW149FWooXGKg8PCpnwpWWkDlKvGay2lxkiGJdXWpSM9ZmZ-5f1wvSksbiSMakn6hkzIprEktOEXTNVzJpMPtJOqts5Ukc7XtaHvGHnETb2wSj5Cz8dYhJERcSP4nlqHx8ACjr9lCs1WJuqtvedgmWCmQwPHwJYkyi5DJqjlbLACKuQEoKPjq8oeFg9Dzbikn76K5aBzCsANP2f6EtnO6HvQdr-I_dCuRlRnIrkk8cvpSAAUiPWQaquTNRSdnJLS6qhbxQWmI5XL17Zhew_6cb2E0i5TEug5lHgl7_u_GeiqtwPdBwqnu3qEY3TQB1qz_ZDadZuVLmHqD__CGizDEX0vjR16BRULAiihygvWLNvdrLd4a9JcjnrWH9N2eNGq6JPi7_wfktQxBmaRaYKmXDYIOSmc3GspIRe0zPqZ-necNAL0pgYsTdM9cGnNjnP0E5BC1u_YmfcxbEscj61cG6Y4RE78h_Z6pF0qX7-nnhdupdAuqV_K-khgDBqv53e9rWxpBYVTOsbJXDxYzE5-xus&amp;cpCustomerId=230614170841718&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686762525.238</value>
      <webElementGuid>af14e2b7-c67c-4bb0-875c-5e35385fb4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>89c2a405-2594-48e0-ad86-51c2ab5bf6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>c68d0ed1-1159-4832-b73d-a19c513ac63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>evergent iframe</value>
      <webElementGuid>bee7da71-244e-4472-908e-bd17b4b0b430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b4c1623-1368-4d6c-a36f-932f06a7bccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[@class=&quot;credit-card-screen row&quot;]/div[@class=&quot;payment-section col&quot;]/iframe[1]</value>
      <webElementGuid>2c210d18-742d-4e49-a29b-2719ef59cccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[3]/iframe</value>
      <webElementGuid>98b7cb68-968f-4a34-aa01-e284d387a63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>2f0693f6-9b14-4ee1-9d6b-b3d738bd1d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://yes-web-stage.evergent.com/checkout?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkZXZpY2VUeXBlIjoiYnJvd3NlciIsImxvYyI6bnVsbCwiYXBpS2V5IjoibE4yR2ZzWU5xRlUxeG5OQjlLTWF1YVYybHlteHlZbEEiLCJ2c3RhdHVzIjpmYWxzZSwibG9naW5UeXBlIjoiQ29udGFjdFVzZXJOYW1lIiwiaXNzIjoiZXYiLCJtb2RlbE5vIjoiMDRyaWVzIiwiY3AiOiJZRVNOVyIsImRldmljZU5hbWUiOiJXZWIiLCJzaWQiOiIyMzA2MTQxNzA4NDE3NTAyMzQwMDQ1NyIsInNlcmlhbE5vIjoiZmY2MWRlZTAtMGFkNS0xMWVlLWI0OTUtYmQ0Y2NiYTk1MzQ5IiwidWlkIjoiMjMwNjE0MTcwODQxNzE4IiwiYXVkIjoiWUVTIiwibmJmIjoxNjg2NzYyNTE2LCJleHAiOjE2ODY3NjYxMjEsImlhdCI6MTY4Njc2MjUyMSwianRpIjoiMVl0WC1FcjExLTBXWk0td2lnNC1jUkFaLTNUTnItNWQiLCJjaWQiOiIzNjYyNDk3MSJ9.DEKLuirxnULyRL8mw6mBtnEOFfbJdXmdxNmMSi210oTZR3EPBxsolfTyWItWwTTdijHxtjVUhS9RRDfDeB5ZoyFvM7LTSXT5AC-XDM90Ici7P7uZWiGoth7C__Ouucnws-0MIWBtOA6J0S7zVesERW149FWooXGKg8PCpnwpWWkDlKvGay2lxkiGJdXWpSM9ZmZ-5f1wvSksbiSMakn6hkzIprEktOEXTNVzJpMPtJOqts5Ukc7XtaHvGHnETb2wSj5Cz8dYhJERcSP4nlqHx8ACjr9lCs1WJuqtvedgmWCmQwPHwJYkyi5DJqjlbLACKuQEoKPjq8oeFg9Dzbikn76K5aBzCsANP2f6EtnO6HvQdr-I_dCuRlRnIrkk8cvpSAAUiPWQaquTNRSdnJLS6qhbxQWmI5XL17Zhew_6cb2E0i5TEug5lHgl7_u_GeiqtwPdBwqnu3qEY3TQB1qz_ZDadZuVLmHqD__CGizDEX0vjR16BRULAiihygvWLNvdrLd4a9JcjnrWH9N2eNGq6JPi7_wfktQxBmaRaYKmXDYIOSmc3GspIRe0zPqZ-necNAL0pgYsTdM9cGnNjnP0E5BC1u_YmfcxbEscj61cG6Y4RE78h_Z6pF0qX7-nnhdupdAuqV_K-khgDBqv53e9rWxpBYVTOsbJXDxYzE5-xus&amp;cpCustomerId=230614170841718&amp;clientId=7777&amp;action=new&amp;currentTimestamp=1686762525.238' and @title = 'evergent iframe']</value>
      <webElementGuid>e202c6b8-2729-4498-9ddc-9b5e2f3f10a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
