<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_239.99_termsconditions</name>
   <tag></tag>
   <elementGuidId>35c1be5f-b062-4f20-9862-a63820b27760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;termsconditions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='termsconditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c5a6943-e5ce-4d1f-8faa-26d2c4863530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss7</value>
      <webElementGuid>b66655f8-96d1-434b-be10-b908ae6ccdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>7ff5f8c5-b42c-4694-ab51-d3ed788c6d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6b21859e-f978-48a1-b0e4-90f59da2009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ab1613e-e7d4-4e45-8717-23434fc15f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>termsconditions</value>
      <webElementGuid>81207a91-e2e9-4ed9-aaed-6a1466af56cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrap h-100&quot;]/div[@class=&quot;checkout_wrapper&quot;]/div[@class=&quot;MuiGrid-root checkout_container py-2 MuiGrid-container MuiGrid-justify-content-xs-center&quot;]/div[@class=&quot;MuiGrid-root paymentMethod_inner&quot;]/div[@class=&quot;jss1&quot;]/form[1]/div[@class=&quot;MuiGrid-root placeOrder_block checkBoxContainer mb-3&quot;]/div[1]/label[@class=&quot;MuiFormControlLabel-root&quot;]/div[1]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss4 MuiCheckbox-root MuiCheckbox-colorSecondary MuiIconButton-colorSecondary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss7&quot;]</value>
      <webElementGuid>1b005c73-f19e-4692-9d15-e47f9581068c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Registration_Subscribe/Page_Watch  YES Network/iframe</value>
      <webElementGuid>ae3b7177-3fb8-4510-8ee6-9a002e1bdf46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='termsconditions']</value>
      <webElementGuid>fe806c90-4c2d-41d2-b1c7-476e378a921e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[3]/div/label/div/span/span/input</value>
      <webElementGuid>a6a70a3a-0d93-49de-860e-0de98be4fbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>0390a075-e792-41f9-9355-31035bc85d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'termsconditions' and @type = 'checkbox']</value>
      <webElementGuid>a2c653a0-8bb3-490c-9af0-0799dc642784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
